# Generated by Django 3.1.5 on 2021-04-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
